package com.soule.evtm.domain;
// Generated Apr 2, 2013 12:06:32 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Appuser generated by hbm2java
 */
@Entity
@Table(name="appuser"
    
)
public class Appuser  implements java.io.Serializable {


     private int appuserid;
     private String fristName;
     private String lastName;
     private String emailId;
     private String password;
     private Set<Contact> contacts = new HashSet<Contact>(0);
     private Set<Event> events = new HashSet<Event>(0);

    public Appuser() {
    }

	
    public Appuser(int appuserid, String fristName, String lastName, String emailId, String password) {
        this.appuserid = appuserid;
        this.fristName = fristName;
        this.lastName = lastName;
        this.emailId = emailId;
        this.password = password;
    }
    public Appuser(int appuserid, String fristName, String lastName, String emailId, String password, Set<Contact> contacts, Set<Event> events) {
       this.appuserid = appuserid;
       this.fristName = fristName;
       this.lastName = lastName;
       this.emailId = emailId;
       this.password = password;
       this.contacts = contacts;
       this.events = events;
    }
   
     @Id 
    
    @Column(name="APPUSERID", unique=true, nullable=false)
    public int getAppuserid() {
        return this.appuserid;
    }
    
    public void setAppuserid(int appuserid) {
        this.appuserid = appuserid;
    }
    
    @Column(name="FristName", nullable=false)
    public String getFristName() {
        return this.fristName;
    }
    
    public void setFristName(String fristName) {
        this.fristName = fristName;
    }
    
    @Column(name="LastName", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="EmailID", nullable=false)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    
    @Column(name="Password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="appuser")
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="appuser")
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }




}


