package com.soule.evtm.domain;
// Generated Mar 26, 2013 12:06:17 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Appuser generated by hbm2java
 */
public class Appuser  implements java.io.Serializable {


     private int appuserid;
     private String fristName;
     private String lastName;
     private String emailId;
     private String password;
     private Set contacts = new HashSet(0);
     private Set events = new HashSet(0);

    public Appuser() {
    }

	
    public Appuser(int appuserid, String fristName, String lastName, String emailId, String password) {
        this.appuserid = appuserid;
        this.fristName = fristName;
        this.lastName = lastName;
        this.emailId = emailId;
        this.password = password;
    }
    public Appuser(int appuserid, String fristName, String lastName, String emailId, String password, Set contacts, Set events) {
       this.appuserid = appuserid;
       this.fristName = fristName;
       this.lastName = lastName;
       this.emailId = emailId;
       this.password = password;
       this.contacts = contacts;
       this.events = events;
    }
   
    public int getAppuserid() {
        return this.appuserid;
    }
    
    public void setAppuserid(int appuserid) {
        this.appuserid = appuserid;
    }
    public String getFristName() {
        return this.fristName;
    }
    
    public void setFristName(String fristName) {
        this.fristName = fristName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set contacts) {
        this.contacts = contacts;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }




}


