package com.soule.evtm.domain;
// Generated Apr 2, 2013 12:06:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    
)
public class Contact  implements java.io.Serializable {


     private int contactId;
     private Appuser appuser;
     private String fristName;
     private String lastName;
     private Integer phoneNo;
     private String address;
     private String emailId;
     private Date createdon;
     private Date modifiedon;
     private Set<Guestlistmap> guestlistmaps = new HashSet<Guestlistmap>(0);
     private Set<Guestevent> guestevents = new HashSet<Guestevent>(0);

    public Contact() {
    }

	
    public Contact(int contactId, String fristName, String lastName, Date createdon, Date modifiedon) {
        this.contactId = contactId;
        this.fristName = fristName;
        this.lastName = lastName;
        this.createdon = createdon;
        this.modifiedon = modifiedon;
    }
    public Contact(int contactId, Appuser appuser, String fristName, String lastName, Integer phoneNo, String address, String emailId, Date createdon, Date modifiedon, Set<Guestlistmap> guestlistmaps, Set<Guestevent> guestevents) {
       this.contactId = contactId;
       this.appuser = appuser;
       this.fristName = fristName;
       this.lastName = lastName;
       this.phoneNo = phoneNo;
       this.address = address;
       this.emailId = emailId;
       this.createdon = createdon;
       this.modifiedon = modifiedon;
       this.guestlistmaps = guestlistmaps;
       this.guestevents = guestevents;
    }
   
     @Id 
    
    @Column(name="ContactID", unique=true, nullable=false)
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APPUSERID")
    public Appuser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(Appuser appuser) {
        this.appuser = appuser;
    }
    
    @Column(name="FristName", nullable=false)
    public String getFristName() {
        return this.fristName;
    }
    
    public void setFristName(String fristName) {
        this.fristName = fristName;
    }
    
    @Column(name="LastName", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="PhoneNo")
    public Integer getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(Integer phoneNo) {
        this.phoneNo = phoneNo;
    }
    
    @Column(name="Address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="EmailID")
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Createdon", nullable=false, length=19)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modifiedon", nullable=false, length=19)
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="contact")
    public Set<Guestlistmap> getGuestlistmaps() {
        return this.guestlistmaps;
    }
    
    public void setGuestlistmaps(Set<Guestlistmap> guestlistmaps) {
        this.guestlistmaps = guestlistmaps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="contact")
    public Set<Guestevent> getGuestevents() {
        return this.guestevents;
    }
    
    public void setGuestevents(Set<Guestevent> guestevents) {
        this.guestevents = guestevents;
    }




}


