package com.soule.evtm.domain;
// Generated Mar 26, 2013 12:06:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private int contactId;
     private Appuser appuser;
     private String fristName;
     private String lastName;
     private Integer phoneNo;
     private String address;
     private String emailId;
     private Date createdon;
     private Date modifiedon;
     private Set guestlistmaps = new HashSet(0);
     private Set guestevents = new HashSet(0);

    public Contact() {
    }

	
    public Contact(int contactId, String fristName, String lastName, Date createdon, Date modifiedon) {
        this.contactId = contactId;
        this.fristName = fristName;
        this.lastName = lastName;
        this.createdon = createdon;
        this.modifiedon = modifiedon;
    }
    public Contact(int contactId, Appuser appuser, String fristName, String lastName, Integer phoneNo, String address, String emailId, Date createdon, Date modifiedon, Set guestlistmaps, Set guestevents) {
       this.contactId = contactId;
       this.appuser = appuser;
       this.fristName = fristName;
       this.lastName = lastName;
       this.phoneNo = phoneNo;
       this.address = address;
       this.emailId = emailId;
       this.createdon = createdon;
       this.modifiedon = modifiedon;
       this.guestlistmaps = guestlistmaps;
       this.guestevents = guestevents;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public Appuser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(Appuser appuser) {
        this.appuser = appuser;
    }
    public String getFristName() {
        return this.fristName;
    }
    
    public void setFristName(String fristName) {
        this.fristName = fristName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(Integer phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
    public Set getGuestlistmaps() {
        return this.guestlistmaps;
    }
    
    public void setGuestlistmaps(Set guestlistmaps) {
        this.guestlistmaps = guestlistmaps;
    }
    public Set getGuestevents() {
        return this.guestevents;
    }
    
    public void setGuestevents(Set guestevents) {
        this.guestevents = guestevents;
    }




}


