package com.soule.evtm.domain;
// Generated Mar 26, 2013 12:06:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer eventId;
     private Appuser appuser;
     private String name;
     private String location;
     private Date date;
     private int subeventId;
     private Date createdon;
     private Date modifiedon;
     private Set guestlists = new HashSet(0);

    public Event() {
    }

	
    public Event(String name, String location, Date date, int subeventId, Date createdon, Date modifiedon) {
        this.name = name;
        this.location = location;
        this.date = date;
        this.subeventId = subeventId;
        this.createdon = createdon;
        this.modifiedon = modifiedon;
    }
    public Event(Appuser appuser, String name, String location, Date date, int subeventId, Date createdon, Date modifiedon, Set guestlists) {
       this.appuser = appuser;
       this.name = name;
       this.location = location;
       this.date = date;
       this.subeventId = subeventId;
       this.createdon = createdon;
       this.modifiedon = modifiedon;
       this.guestlists = guestlists;
    }
   
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }
    public Appuser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(Appuser appuser) {
        this.appuser = appuser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getSubeventId() {
        return this.subeventId;
    }
    
    public void setSubeventId(int subeventId) {
        this.subeventId = subeventId;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
    public Set getGuestlists() {
        return this.guestlists;
    }
    
    public void setGuestlists(Set guestlists) {
        this.guestlists = guestlists;
    }




}


