package com.soule.evtm.domain;
// Generated Mar 26, 2013 12:06:17 AM by Hibernate Tools 3.2.1.GA



/**
 * Guestlistmap generated by hbm2java
 */
public class Guestlistmap  implements java.io.Serializable {


     private int guestListMapId;
     private Guestlist guestlist;
     private Contact contact;

    public Guestlistmap() {
    }

	
    public Guestlistmap(int guestListMapId) {
        this.guestListMapId = guestListMapId;
    }
    public Guestlistmap(int guestListMapId, Guestlist guestlist, Contact contact) {
       this.guestListMapId = guestListMapId;
       this.guestlist = guestlist;
       this.contact = contact;
    }
   
    public int getGuestListMapId() {
        return this.guestListMapId;
    }
    
    public void setGuestListMapId(int guestListMapId) {
        this.guestListMapId = guestListMapId;
    }
    public Guestlist getGuestlist() {
        return this.guestlist;
    }
    
    public void setGuestlist(Guestlist guestlist) {
        this.guestlist = guestlist;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }




}


