package com.soule.evtm.domain;
// Generated Apr 2, 2013 12:06:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Guestevent generated by hbm2java
 */
@Entity
@Table(name="guestevent"
    
)
public class Guestevent  implements java.io.Serializable {


     private int guestEventId;
     private Guestlist guestlist;
     private Contact contact;

    public Guestevent() {
    }

	
    public Guestevent(int guestEventId) {
        this.guestEventId = guestEventId;
    }
    public Guestevent(int guestEventId, Guestlist guestlist, Contact contact) {
       this.guestEventId = guestEventId;
       this.guestlist = guestlist;
       this.contact = contact;
    }
   
     @Id 
    
    @Column(name="GuestEventID", unique=true, nullable=false)
    public int getGuestEventId() {
        return this.guestEventId;
    }
    
    public void setGuestEventId(int guestEventId) {
        this.guestEventId = guestEventId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GuestListID")
    public Guestlist getGuestlist() {
        return this.guestlist;
    }
    
    public void setGuestlist(Guestlist guestlist) {
        this.guestlist = guestlist;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ContactID")
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }




}


