package com.soule.evtm.domain;
// Generated Apr 2, 2013 12:06:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Guestlist generated by hbm2java
 */
@Entity
@Table(name="guestlist"
    
)
public class Guestlist  implements java.io.Serializable {


     private int guestListId;
     private Event event;
     private String guestListName;
     private Date createdon;
     private Date modifiedon;
     private Set<Guestlistmap> guestlistmaps = new HashSet<Guestlistmap>(0);
     private Set<Guestevent> guestevents = new HashSet<Guestevent>(0);

    public Guestlist() {
    }

	
    public Guestlist(int guestListId, String guestListName, Date createdon, Date modifiedon) {
        this.guestListId = guestListId;
        this.guestListName = guestListName;
        this.createdon = createdon;
        this.modifiedon = modifiedon;
    }
    public Guestlist(int guestListId, Event event, String guestListName, Date createdon, Date modifiedon, Set<Guestlistmap> guestlistmaps, Set<Guestevent> guestevents) {
       this.guestListId = guestListId;
       this.event = event;
       this.guestListName = guestListName;
       this.createdon = createdon;
       this.modifiedon = modifiedon;
       this.guestlistmaps = guestlistmaps;
       this.guestevents = guestevents;
    }
   
     @Id 
    
    @Column(name="GuestListID", unique=true, nullable=false)
    public int getGuestListId() {
        return this.guestListId;
    }
    
    public void setGuestListId(int guestListId) {
        this.guestListId = guestListId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EventID")
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    
    @Column(name="GuestListName", nullable=false)
    public String getGuestListName() {
        return this.guestListName;
    }
    
    public void setGuestListName(String guestListName) {
        this.guestListName = guestListName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Createdon", nullable=false, length=19)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modifiedon", nullable=false, length=19)
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="guestlist")
    public Set<Guestlistmap> getGuestlistmaps() {
        return this.guestlistmaps;
    }
    
    public void setGuestlistmaps(Set<Guestlistmap> guestlistmaps) {
        this.guestlistmaps = guestlistmaps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="guestlist")
    public Set<Guestevent> getGuestevents() {
        return this.guestevents;
    }
    
    public void setGuestevents(Set<Guestevent> guestevents) {
        this.guestevents = guestevents;
    }




}


