package com.soule.evtm.domain;
// Generated Apr 2, 2013 12:06:32 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Guestlistmap generated by hbm2java
 */
@Entity
@Table(name="guestlistmap"
    
)
public class Guestlistmap  implements java.io.Serializable {


     private int guestListMapId;
     private Guestlist guestlist;
     private Contact contact;

    public Guestlistmap() {
    }

	
    public Guestlistmap(int guestListMapId) {
        this.guestListMapId = guestListMapId;
    }
    public Guestlistmap(int guestListMapId, Guestlist guestlist, Contact contact) {
       this.guestListMapId = guestListMapId;
       this.guestlist = guestlist;
       this.contact = contact;
    }
   
     @Id 
    
    @Column(name="GuestListMapID", unique=true, nullable=false)
    public int getGuestListMapId() {
        return this.guestListMapId;
    }
    
    public void setGuestListMapId(int guestListMapId) {
        this.guestListMapId = guestListMapId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GuestListID")
    public Guestlist getGuestlist() {
        return this.guestlist;
    }
    
    public void setGuestlist(Guestlist guestlist) {
        this.guestlist = guestlist;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ContactID")
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }




}


