package com.soule.evtm.domain;
// Generated Mar 26, 2013 12:06:17 AM by Hibernate Tools 3.2.1.GA



/**
 * Guestevent generated by hbm2java
 */
public class Guestevent  implements java.io.Serializable {


     private int guestEventId;
     private Guestlist guestlist;
     private Contact contact;

    public Guestevent() {
    }

	
    public Guestevent(int guestEventId) {
        this.guestEventId = guestEventId;
    }
    public Guestevent(int guestEventId, Guestlist guestlist, Contact contact) {
       this.guestEventId = guestEventId;
       this.guestlist = guestlist;
       this.contact = contact;
    }
   
    public int getGuestEventId() {
        return this.guestEventId;
    }
    
    public void setGuestEventId(int guestEventId) {
        this.guestEventId = guestEventId;
    }
    public Guestlist getGuestlist() {
        return this.guestlist;
    }
    
    public void setGuestlist(Guestlist guestlist) {
        this.guestlist = guestlist;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }




}


